### EDA
This note book looks through different csv files containing nutrient data. The hope is to link it with health issues including but not limited to Malnutrition and Obesity.

It will focus on one file per "cycle"

In [18]:
import pandas as pd


df = pd.read_csv('data/nndb_flat.csv')
df

,ID,FoodGroup,ShortDescrip,Descrip,CommonName,MfgName,ScientificName,Energy_kcal,Protein_g,Fat_g,...,Folate_USRDA,Niacin_USRDA,Riboflavin_USRDA,Thiamin_USRDA,Calcium_USRDA,Copper_USRDA,Magnesium_USRDA,Phosphorus_USRDA,Selenium_USRDA,Zinc_USRDA
0,1001,Dairy and Egg Products,"BUTTER,WITH SALT","Butter, salted",NaN,NaN,NaN,717.0,0.85,81.11,...,0.0075,0.002625,0.026154,0.004167,0.020000,0.000000,0.004762,0.034286,0.018182,0.008182
1,1002,Dairy and Egg Products,"BUTTER,WHIPPED,WITH SALT","Butter, whipped, with salt",NaN,NaN,NaN,717.0,0.85,81.11,...,0.0075,0.002625,0.026154,0.004167,0.020000,0.000018,0.004762,0.032857,0.018182,0.004545
2,1003,Dairy and Egg Products,"BUTTER OIL,ANHYDROUS","Butter oil, anhydrous",NaN,NaN,NaN,876.0,0.28,99.48,...,0.0000,0.000188,0.003846,0.000833,0.003333,0.000001,0.000000,0.004286,0.000000,0.000909
3,1004,Dairy and Egg Products,"CHEESE,BLUE","Cheese, blue",NaN,NaN,NaN,353.0,21.40,28.74,...,0.0900,0.063500,0.293846,0.024167,0.440000,0.000044,0.054762,0.552857,0.263636,0.241818
4,1005,Dairy and Egg Products,"CHEESE,BRICK","Cheese, brick",NaN,NaN,NaN,371.0,23.24,29.68,...,0.0500,0.007375,0.270000,0.011667,0.561667,0.000027,0.057143,0.644286,0.263636,0.236364
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8613,83110,Finfish and Shellfish Products,"MACKEREL,SALTED","Fish, mackerel, salted",NaN,NaN,NaN,305.0,18.50,25.10,...,0.0375,0.206250,0.146154,0.016667,0.055000,0.000111,0.142857,0.362857,1.334545,0.100000
8614,90240,Finfish and Shellfish Products,"SCALLOP,(BAY&SEA),CKD,STMD","Mollusks, scallop, (bay and sea), cooked, steamed",NaN,NaN,NaN,111.0,20.54,0.84,...,0.0500,0.067250,0.018462,0.010000,0.008333,0.000037,0.088095,0.608571,0.394545,0.140909
8615,90480,Sweets,"SYRUP,CANE","Syrup, Cane",NaN,NaN,NaN,269.0,0.00,0.00,...,0.0000,0.006250,0.046154,0.108333,0.010833,0.000022,0.023810,0.011429,0.012727,0.017273
8616,90560,Finfish and Shellfish Products,"SNAIL,RAW","Mollusks, snail, raw",NaN,NaN,NaN,90.0,16.10,1.40,...,0.0150,0.087500,0.092308,0.008333,0.008333,0.000444,0.595238,0.388571,0.498182,0.090909
8617,93600,Finfish and Shellfish Products,"TURTLE,GREEN,RAW","Turtle, green, raw",NaN,NaN,NaN,89.0,19.80,0.50,...,0.0375,0.068750,0.115385,0.100000,0.098333,0.000278,0.047619,0.257143,0.305455,0.090909

#### Checking datatypes

In [19]:
df.dtypes

ID                    int64
FoodGroup            object
ShortDescrip         object
Descrip              object
CommonName           object
MfgName              object
ScientificName       object
Energy_kcal         float64
Protein_g           float64
Fat_g               float64
Carb_g              float64
Sugar_g             float64
Fiber_g             float64
VitA_mcg            float64
VitB6_mg            float64
VitB12_mcg          float64
VitC_mg             float64
VitE_mg             float64
Folate_mcg          float64
Niacin_mg           float64
Riboflavin_mg       float64
Thiamin_mg          float64
Calcium_mg          float64
Copper_mcg          float64
Iron_mg             float64
Magnesium_mg        float64
Manganese_mg        float64
Phosphorus_mg       float64
Selenium_mcg        float64
Zinc_mg             float64
VitA_USRDA          float64
VitB6_USRDA         float64
VitB12_USRDA        float64
VitC_USRDA          float64
VitE_USRDA          float64
Folate_USRDA        float64
Niacin_USRDA        float64
Riboflavin_USRDA    float64
Thiamin_USRDA       float64
Calcium_USRDA       float64
Copper_USRDA        float64
Magnesium_USRDA     float64
Phosphorus_USRDA    float64
Selenium_USRDA      float64
Zinc_USRDA          float64
dtype: object

### Dealing with nulls

In [20]:
df.isna()

,ID,FoodGroup,ShortDescrip,Descrip,CommonName,MfgName,ScientificName,Energy_kcal,Protein_g,Fat_g,...,Folate_USRDA,Niacin_USRDA,Riboflavin_USRDA,Thiamin_USRDA,Calcium_USRDA,Copper_USRDA,Magnesium_USRDA,Phosphorus_USRDA,Selenium_USRDA,Zinc_USRDA
0,False,False,False,False,True,True,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,True,True,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,True,True,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,True,True,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,True,True,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8613,False,False,False,False,True,True,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8614,False,False,False,False,True,True,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8615,False,False,False,False,True,True,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8616,False,False,False,False,True,True,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8617,False,False,False,False,True,True,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [21]:
# notcommited to this step as it might cause wrong data brought forward 
for col in df:
    if df[col].isnull().sum() > 0:
        try:
            df[col].fillna(df[col].mean(), inplace = True)
        except:
            df[col].fillna(df[col].mode()[0],inplace = True)


df

,ID,FoodGroup,ShortDescrip,Descrip,CommonName,MfgName,ScientificName,Energy_kcal,Protein_g,Fat_g,...,Folate_USRDA,Niacin_USRDA,Riboflavin_USRDA,Thiamin_USRDA,Calcium_USRDA,Copper_USRDA,Magnesium_USRDA,Phosphorus_USRDA,Selenium_USRDA,Zinc_USRDA
0,1001,Dairy and Egg Products,"BUTTER,WITH SALT","Butter, salted",hamburger,"Kellogg, Co.",Phaseolus vulgaris,717.0,0.85,81.11,...,0.0075,0.002625,0.026154,0.004167,0.020000,0.000000,0.004762,0.034286,0.018182,0.008182
1,1002,Dairy and Egg Products,"BUTTER,WHIPPED,WITH SALT","Butter, whipped, with salt",hamburger,"Kellogg, Co.",Phaseolus vulgaris,717.0,0.85,81.11,...,0.0075,0.002625,0.026154,0.004167,0.020000,0.000018,0.004762,0.032857,0.018182,0.004545
2,1003,Dairy and Egg Products,"BUTTER OIL,ANHYDROUS","Butter oil, anhydrous",hamburger,"Kellogg, Co.",Phaseolus vulgaris,876.0,0.28,99.48,...,0.0000,0.000188,0.003846,0.000833,0.003333,0.000001,0.000000,0.004286,0.000000,0.000909
3,1004,Dairy and Egg Products,"CHEESE,BLUE","Cheese, blue",hamburger,"Kellogg, Co.",Phaseolus vulgaris,353.0,21.40,28.74,...,0.0900,0.063500,0.293846,0.024167,0.440000,0.000044,0.054762,0.552857,0.263636,0.241818
4,1005,Dairy and Egg Products,"CHEESE,BRICK","Cheese, brick",hamburger,"Kellogg, Co.",Phaseolus vulgaris,371.0,23.24,29.68,...,0.0500,0.007375,0.270000,0.011667,0.561667,0.000027,0.057143,0.644286,0.263636,0.236364
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8613,83110,Finfish and Shellfish Products,"MACKEREL,SALTED","Fish, mackerel, salted",hamburger,"Kellogg, Co.",Phaseolus vulgaris,305.0,18.50,25.10,...,0.0375,0.206250,0.146154,0.016667,0.055000,0.000111,0.142857,0.362857,1.334545,0.100000
8614,90240,Finfish and Shellfish Products,"SCALLOP,(BAY&SEA),CKD,STMD","Mollusks, scallop, (bay and sea), cooked, steamed",hamburger,"Kellogg, Co.",Phaseolus vulgaris,111.0,20.54,0.84,...,0.0500,0.067250,0.018462,0.010000,0.008333,0.000037,0.088095,0.608571,0.394545,0.140909
8615,90480,Sweets,"SYRUP,CANE","Syrup, Cane",hamburger,"Kellogg, Co.",Phaseolus vulgaris,269.0,0.00,0.00,...,0.0000,0.006250,0.046154,0.108333,0.010833,0.000022,0.023810,0.011429,0.012727,0.017273
8616,90560,Finfish and Shellfish Products,"SNAIL,RAW","Mollusks, snail, raw",hamburger,"Kellogg, Co.",Phaseolus vulgaris,90.0,16.10,1.40,...,0.0150,0.087500,0.092308,0.008333,0.008333,0.000444,0.595238,0.388571,0.498182,0.090909
8617,93600,Finfish and Shellfish Products,"TURTLE,GREEN,RAW","Turtle, green, raw",hamburger,"Kellogg, Co.",Phaseolus vulgaris,89.0,19.80,0.50,...,0.0375,0.068750,0.115385,0.100000,0.098333,0.000278,0.047619,0.257143,0.305455,0.090909

### Dealing with categorical data

In [22]:
df = pd.get_dummies(df, columns=['FoodGroup'])
df = pd.get_dummies(df, columns=['ScientificName'])

df

,ID,ShortDescrip,Descrip,CommonName,MfgName,Energy_kcal,Protein_g,Fat_g,Carb_g,Sugar_g,...,ScientificName_Vitis vinifera,ScientificName_Wasabia japonica,ScientificName_X Triticosecale spp.,ScientificName_Xanthosoma sagittifolium,ScientificName_Xiphias gladius L.,ScientificName_Zea mays,ScientificName_Zea mays mays L.,ScientificName_Zingiber officinale,ScientificName_Zizania spp.,ScientificName_Ziziphus jujuba
0,1001,"BUTTER,WITH SALT","Butter, salted",hamburger,"Kellogg, Co.",717.0,0.85,81.11,0.06,0.06,...,0,0,0,0,0,0,0,0,0,0
1,1002,"BUTTER,WHIPPED,WITH SALT","Butter, whipped, with salt",hamburger,"Kellogg, Co.",717.0,0.85,81.11,0.06,0.06,...,0,0,0,0,0,0,0,0,0,0
2,1003,"BUTTER OIL,ANHYDROUS","Butter oil, anhydrous",hamburger,"Kellogg, Co.",876.0,0.28,99.48,0.00,0.00,...,0,0,0,0,0,0,0,0,0,0
3,1004,"CHEESE,BLUE","Cheese, blue",hamburger,"Kellogg, Co.",353.0,21.40,28.74,2.34,0.50,...,0,0,0,0,0,0,0,0,0,0
4,1005,"CHEESE,BRICK","Cheese, brick",hamburger,"Kellogg, Co.",371.0,23.24,29.68,2.79,0.51,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8613,83110,"MACKEREL,SALTED","Fish, mackerel, salted",hamburger,"Kellogg, Co.",305.0,18.50,25.10,0.00,0.00,...,0,0,0,0,0,0,0,0,0,0
8614,90240,"SCALLOP,(BAY&SEA),CKD,STMD","Mollusks, scallop, (bay and sea), cooked, steamed",hamburger,"Kellogg, Co.",111.0,20.54,0.84,5.41,0.00,...,0,0,0,0,0,0,0,0,0,0
8615,90480,"SYRUP,CANE","Syrup, Cane",hamburger,"Kellogg, Co.",269.0,0.00,0.00,73.14,73.20,...,0,0,0,0,0,0,0,0,0,0
8616,90560,"SNAIL,RAW","Mollusks, snail, raw",hamburger,"Kellogg, Co.",90.0,16.10,1.40,2.00,0.00,...,0,0,0,0,0,0,0,0,0,0
8617,93600,"TURTLE,GREEN,RAW","Turtle, green, raw",hamburger,"Kellogg, Co.",89.0,19.80,0.50,0.00,0.00,...,0,0,0,0,0,0,0,0,0,0

### Trying a predictive model

In [23]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

X = df.drop(['ID', 'ShortDescrip', 'Descrip', 'CommonName', 'MfgName'], axis=1)
y = df['Energy_kcal']

#spli into testing and training data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [24]:
# create the model 
model = LinearRegression()

# fit the model on the training data
model.fit(X_train, y_train)

LinearRegression()

In [25]:
y_pred = model.predict(X_test)
r2 = r2_score(y_test, y_pred)
print("R^2 score:", r2)

R^2 score: 1.0

In [26]:
y_pred_train= model.predict(X_train)
r2 = r2_score(y_train, y_pred_train)
print("R^2 score:", r2)

R^2 score: 1.0

### Beginning of of Cycle 2 
Different dataset

In [117]:
# df2 = pd.read_csv('data/NutritionalFacts_Fruit_Vegetables_Seafood.csv')
# df2

In [69]:
# df2.dtypes

Food and Serving          object
Calories                 float64
Calories  from Fat       float64
Total Fat                 object
Total Fat.1               object
Sodium                    object
Sodium.1                  object
Potassium                 object
Potassium.1               object
Total Carbo-hydrate       object
Total Carbo-hydrate.1     object
Dietary Fiber             object
Dietary Fiber.1           object
Sugars                    object
Protein                   object
Vitamin A                 object
Vitamin C                 object
Calcium                   object
    Iron                  object
Saturated Fat             object
Saturated Fat.1           object
Chole-sterol              object
Chole-sterol.1            object
Food Type                 object
dtype: object

In [70]:
# df2.isnull()

,Food and Serving,Calories,Calories from Fat,Total Fat,Total Fat.1,Sodium,Sodium.1,Potassium,Potassium.1,Total Carbo-hydrate,...,Protein,Vitamin A,Vitamin C,Calcium,Iron,Saturated Fat,Saturated Fat.1,Chole-sterol,Chole-sterol.1,Food Type
0,True,True,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,True,True,True,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,True,True,True,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,True,True,True,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,True,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
58,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
59,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
60,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
61,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [118]:
# # handle conflicting datatypes and missing values
# for col in df2.columns:
#     if df2[col].dtype == 'object':
#         df2[col].fillna(df2[col].mode()[0], inplace=True)
#     else:
# #         df2[col] = pd.to_numeric(df2[col], errors='coerce')
#         df2[col].fillna(df2[col].mean(), inplace=True)
        
# df

In [119]:
# import pandas as pd
# from sklearn.preprocessing import LabelEncoder



# # split the "Food and Serving" column into "Food" and "Serving" columns
# df2[['Food', 'Serving']] = df2['Food and Serving'].str.split(',', n=1, expand=True)

# # drop the original "Food and Serving" column
# df2.drop('Food and Serving', axis=1, inplace=True)

# def serving_size_to_float(serving_size):
#     if serving_size is None:
#         return float(0)
#     try:
#         return float(serving_size.strip(' g'))
#     except ValueError:
#         return float(0)


# df2['Serving Size (g)'] = df2['Serving'].apply(serving_size_to_float)
# df2.drop('Serving', axis=1, inplace=True)

# # encode food names using label encoding
# df2[['Food', 'Type']] = df2['Food Type'].str.split(',', n=1, expand=True)

# le_food = LabelEncoder()
# df2['Food Encoded'] = le_food.fit_transform(df2['Food'])
# le_type = LabelEncoder()
# df2['Type Encoded'] = le_type.fit_transform(df2['Type'])

# # Print the modified dataframe
# df2.head(10)

In [113]:

# df2 = pd.get_dummies(df2, columns=['Food'])

In [120]:
# # Split the data into training and testing sets
# X_train, X_test, y_train, y_test = train_test_split(df2.drop('Food Type', axis=1), df2['Food Type'], test_size=0.2, random_state=42)

# # Train the model
# model2 = LinearRegression()
# model2.fit(X_train, y_train)

# # Evaluate the model
# print(f'Training Score: {model2.score(X_train, y_train)}')
# print(f'Testing Score: {model2.score(X_test, y_test)}')